import { ArrowLeft, Scale, AlertOctagon, CheckCircle2, ShieldAlert } from 'lucide-react'

interface PageProps {
  onNavigate: (path: string) => void
}

export function TermsPage({ onNavigate }: PageProps) {
  return (
    <div className="shell page-container" style={{ padding: '40px 0 80px', maxWidth: '840px', margin: '0 auto' }}>
      <button 
        type="button" 
        onClick={() => onNavigate('/')} 
        className="button button-quiet small"
        style={{ marginBottom: '24px' }}
      >
        <ArrowLeft size={16} /> Back to Planning Workbench
      </button>

      <div className="page-header" style={{ marginBottom: '32px' }}>
        <p className="eyebrow"><span /> Governance & Operational Guidelines</p>
        <h1 style={{ fontSize: '38px', margin: '8px 0 16px', color: '#103631' }}>
          Terms of Service & Model Governance
        </h1>
        <p style={{ color: '#54726b', fontSize: '16px', lineHeight: 1.6 }}>
          CivicPriorities is an open-source civic decision-support instrument designed to aid transparent municipal budgeting. Use of this system requires adherence to the following governance rules.
        </p>
      </div>

      <div className="terms-grid" style={{ display: 'grid', gap: '20px', marginBottom: '36px' }}>
        <article className="panel" style={{ background: '#ffffff' }}>
          <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', color: '#14463e', marginBottom: '8px' }}>
            <Scale size={18} color="#188574" /> 1. Advisory Decision Support, Not Automated Spending
          </h3>
          <p style={{ color: '#4d6963', fontSize: '14px', lineHeight: 1.6, margin: 0 }}>
            Rankings, priority scores, and greedy budget shortlists generated by this engine are recommendations for human planners. Under no circumstances should this system be connected to autonomous municipal treasury disbursements without human oversight.
          </p>
        </article>

        <article className="panel" style={{ background: '#ffffff' }}>
          <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', color: '#14463e', marginBottom: '8px' }}>
            <AlertOctagon size={18} color="#188574" /> 2. The Evidence-Gating Invariant
          </h3>
          <p style={{ color: '#4d6963', fontSize: '14px', lineHeight: 1.6, margin: 0 }}>
            In accordance with participatory DPG standards, missing infrastructure inventory or population denominators must <strong>block</strong> a project candidate from receiving an algorithmic rank. The system strictly prohibits substituting missing baseline paperwork with zero-scores.
          </p>
        </article>

        <article className="panel" style={{ background: '#ffffff' }}>
          <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', color: '#14463e', marginBottom: '8px' }}>
            <CheckCircle2 size={18} color="#188574" /> 3. Human Review & Revision Conflict Protection
          </h3>
          <p style={{ color: '#4d6963', fontSize: '14px', lineHeight: 1.6, margin: 0 }}>
            All formal endorsements require verified planner or auditor credentials. The backend verifies sequential revisions; any concurrent modification to a planning run will trigger an HTTP 409 Conflict to prevent race conditions.
          </p>
        </article>

        <article className="panel" style={{ background: '#ffffff' }}>
          <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', color: '#14463e', marginBottom: '8px' }}>
            <ShieldAlert size={18} color="#188574" /> 4. AI & Multilingual Model Limitations
          </h3>
          <p style={{ color: '#4d6963', fontSize: '14px', lineHeight: 1.6, margin: 0 }}>
            Category extractions and AI rationales generated via Google Gemini or local rule engines are provided with visible span quotes. Operators must inspect extracted quotes before confirming citizen requests into the active planning ledger.
          </p>
        </article>
      </div>

      <div style={{ borderTop: '1px solid #d5e4dc', paddingTop: '20px', color: '#688680', fontSize: '13px' }}>
        Licensed under the Apache 2.0 / MIT Open Source License. Built for municipal transparency research and participatory budgeting demonstrations.
      </div>
    </div>
  )
}
